# Generated by Django 2.2 on 2021-03-28 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210326_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ask',
            new_name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
