# Generated by Django 2.2 on 2021-03-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210328_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='ask',
        ),
        migrations.RemoveField(
            model_name='question',
            name='datetime',
        ),
    ]
