# Generated by Django 2.2 on 2021-04-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210328_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_name',
            field=models.CharField(default='Guest', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='question',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='ask',
            field=models.CharField(max_length=20),
        ),
    ]
