# Generated by Django 2.2 on 2021-04-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210403_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask',
            field=models.CharField(max_length=250),
        ),
    ]
