# Generated by Django 2.2 on 2021-04-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_is_collegeverfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_collegeverfied',
            field=models.BooleanField(default=False),
        ),
    ]
