# Generated by Django 2.2 on 2021-04-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_collegeverfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_collegeverfied',
            new_name='is_collegeverified',
        ),
    ]
