# Generated by Django 2.2 on 2021-04-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210404_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
    ]
