# Generated by Django 2.2 on 2021-04-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='nil', max_length=30),
        ),
    ]
